name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-slim
    steps:
      - name: Merge and build v1 branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCH: v1
        run: |
          git clone https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git repo
          cd repo

          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"

          git checkout $RELEASE_BRANCH
          git pull --rebase
          git merge master

          npm install
          npm run build

          git add dist/
          git commit --allow-empty -m "build: release $(git rev-parse master)"
          git push origin $RELEASE_BRANCH
