name: create-release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  create-tag:
    runs-on: mi-gha-runner-generic
    name: create-tag
    steps:
      - uses: actions/checkout@v6
      - name: tag-version
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v1.0.1
          tag_prefix: ""

  create-github-release:
    needs: create-tag
    runs-on: mi-gha-runner-generic
    name: create-github-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          tag_name: v1.0.1
          token: ${{ secrets.GITHUB_TOKEN }}
