name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Merge release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts

          git config --global user.email "release@movableink.com"
          git config --global user.name "Movable Ink Release"

          git clone https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/movableink/pr-clubhouse-lint-action.git
          cd pr-clubhouse-lint-action

          git checkout release
          git pull --rebase
          git merge master

          rm -Rf node_modules
          npm install --production

          du -h --max-depth=1 .

          git add .
          git commit --allow-empty -m "vendored release for $(git rev-parse master)"
          git push origin release
