name: Release
on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Merge release branch
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          echo "${GIT_DEPLOY_KEY}" > ~/.ssh/id_rsa
          git checkout release
          git pull --rebase
          rm -Rf node_modules
          git merge master
          npm install --production
          git add .
          git commit -m 'release'
          # git push
